04-lection2 solution
js-tasks-ru/htmlcss-20220616_marina-gichyan pull request #5
Opened 2022-06-27 10:58 UTC by MarinaGichian

В гистограмме не поняла как сделать div полностью кликабельным (с  <a> получается кликабельным только текст)

2022-06-27 10:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-27 14:38 UTC, GSemikozov requested changes

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 1110px;
не нужно)
если надо будет - мы просто встроим гистограмму в контейнер.

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width: 1110px;
а вот что здесь действительно нужно - паддинги, чтобы не задавать одни и те же отступы на уровне дочерних элементов

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 24px;
про это - выше

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart {
это не отдельный блок, а элемент блока Гистограмма, поэтому - .histogram__chart

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее, у нас уже есть gap

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
не указана высота данного элемента (50px)

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.chart__column {
.histogram__chart-column

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 10px;
лишнее, лучше по умолчанию просто остается как есть

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <div style="height: 50px;" class="chart__column"></div>
если на родителе зададим 50px - то тогда здесь уже относительно этой высоты можно будет указывать высоту колонок в процентах, что более предпочтительно

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 1110px;
этот момент + паддинги - аналогично с Гистограммой

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-right: 50%;
здесь нужно модифицировать не отступ, а ширину

2022-06-27 14:38 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-right: 25%;
и здесь

2022-06-27 21:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-28 19:42 UTC, MarinaGichian commented
test

2022-06-28 19:49 UTC, MarinaGichian commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-right: 25%;
а можно подробнее про то, как модифицировать правильно? 
я поправила margin на width в процентах, но  не совсем понимаю как оно работает: я указываю ширину в процентах - и это сработало, но от чего берутся проценты, ведь в родительском блоке у нас нет ширины фиксированной (и нет display flex). Тогда как он считает?

2022-06-28 20:04 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-right: 25%;
проценты работают относительно размера родителя)

2022-06-28 20:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-right: 25%;
фиксированной ширины нет, но браузер сам понимает какая там текущая ширина, от нее и отталкивается. Мы это тоже можем проверить - открыть devtools, навести на элемент - и увидим его текущие размеры

2022-06-28 20:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-06-29 15:18 UTC, GSemikozov approved these changes

2022-06-29 15:18 UTC, merged